name: 'Simple project'
permission:
  actions: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches: ["feature/*"]
    paths:
    - 'frontend/**'
    - 'catalog/**'
    - 'ordering/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: action/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
